# Generated by Django 3.2 on 2023-03-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20230315_1129'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='modelrestaurant',
            table=None,
        ),
    ]
