# Generated by Django 3.2 on 2023-03-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_alter_modelrestaurant_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelrestaurant',
            options={'managed': False},
        ),
    ]
